"""Render scope helpers and safe prune protection."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ingest_review.review_queue_status import status_from_artifact
from src.wiki_render.collect import collect_items
from src.wiki_render.loader import load_review_artifacts
from src.wiki_render.merge import build_knowledge_graph
from src.wiki_render.models import KnowledgeGraph, RenderedFile
from src.wiki_render.render import render_graph


def load_in_progress_review_artifacts(reviews_dir: Path) -> list[dict[str, Any]]:
    """Return only in-progress review artifacts."""
    return [
        artifact
        for artifact in load_review_artifacts(reviews_dir, include_in_progress=True)
        if status_from_artifact(artifact) == "in_progress"
    ]


def render_artifacts(
    artifacts: list[dict[str, Any]],
    *,
    wiki_dir: Path,
    raw_dir: Path,
    repo_root: Path,
    synthesis_cache_dir: Path,
    taxonomy_version: str,
    include_synthesis_indexes: bool = True,
) -> tuple[KnowledgeGraph, list[RenderedFile]]:
    """Build the knowledge graph and rendered files for one artifact set."""
    collected = collect_items(artifacts, wiki_dir)
    graph = build_knowledge_graph(
        collected,
        wiki_dir=wiki_dir,
        taxonomy_version=taxonomy_version,
    )
    rendered = render_graph(
        graph,
        wiki_dir=wiki_dir,
        raw_dir=raw_dir,
        repo_root=repo_root,
        synthesis_cache_dir=synthesis_cache_dir,
        include_synthesis_indexes=include_synthesis_indexes,
    )
    return graph, rendered


def protected_prune_paths_for_in_progress(
    *,
    reviews_dir: Path,
    wiki_dir: Path,
    raw_dir: Path,
    repo_root: Path,
    synthesis_cache_dir: Path,
    taxonomy_version: str,
) -> set[str]:
    """Return paths generated by in-progress reviews that must not be pruned.

    When the active render scope is finished-only, these files may still exist on
    disk from earlier preview renders. They are excluded from prune so partial
    review work is never deleted accidentally.
    """
    artifacts = load_in_progress_review_artifacts(reviews_dir)
    if not artifacts:
        return set()
    _graph, rendered = render_artifacts(
        artifacts,
        wiki_dir=wiki_dir,
        raw_dir=raw_dir,
        repo_root=repo_root,
        synthesis_cache_dir=synthesis_cache_dir,
        taxonomy_version=taxonomy_version,
        include_synthesis_indexes=False,
    )
    return {item.relative_path for item in rendered}
