tags:
- agentic-coding
- classification
- customer-service
- embedding-model
- images
- interactive-ai
- it-security
- local-model-deployment
- multi-modal
- open-weight
- proprietary
- realtime-voice-model
