"""Shared wiki generation and validation contract definitions."""

from __future__ import annotations

from src.wiki_contract.categories import (
    CATEGORY_BY_FRONTMATTER,
    CATEGORY_BY_GRAPH,
    DERIVED_KEY_BY_GRAPH_CATEGORY,
    EVIDENCE_GRAPH_CATEGORIES,
    FRONTMATTER_CATEGORY_BY_GRAPH,
    MERGED_GRAPH_CATEGORIES,
    CategorySpec,
    all_category_specs,
    derived_key_for_graph_category,
    graph_category_for_frontmatter,
    spec_for_frontmatter,
    spec_for_graph,
)
from src.wiki_contract.frontmatter import (
    DERIVED_FRONTMATTER_KEYS,
    REQUIRED_FIELDS_BY_FRONTMATTER,
    required_fields_for,
)
from src.wiki_contract.headings import (
    EVIDENCE_SECTION_HEADING,
    MERGED_KNOWLEDGE_SECTION_HEADINGS,
    SOURCE_H2_HEADINGS,
    required_h2_headings_for,
)
from src.wiki_contract.layout import (
    FOUNDATION_MODELS,
    GLOSSARY,
    HOW_TO,
    IMPLEMENTATION_STUDIES,
    INDEXES,
    INDUSTRY_TRENDS,
    INTERVIEW_INSIGHTS,
    LEGACY_MANUAL_INGEST,
    MANAGED_FOLDERS,
    NOTES,
    PRESERVED_ROOT_FILES,
    PRESERVED_WIKI_PREFIXES,
    SIGNALS,
    SOURCES,
    TOOLS,
    TOPICS,
    category_folder_for_graph,
    is_lint_skipped_path,
    is_managed_relative_path,
    is_preserved_wiki_path,
)

__all__ = [
    "CATEGORY_BY_FRONTMATTER",
    "CATEGORY_BY_GRAPH",
    "DERIVED_FRONTMATTER_KEYS",
    "DERIVED_KEY_BY_GRAPH_CATEGORY",
    "EVIDENCE_GRAPH_CATEGORIES",
    "EVIDENCE_SECTION_HEADING",
    "FOUNDATION_MODELS",
    "FRONTMATTER_CATEGORY_BY_GRAPH",
    "GLOSSARY",
    "HOW_TO",
    "IMPLEMENTATION_STUDIES",
    "INDEXES",
    "INDUSTRY_TRENDS",
    "INTERVIEW_INSIGHTS",
    "LEGACY_MANUAL_INGEST",
    "MANAGED_FOLDERS",
    "MERGED_GRAPH_CATEGORIES",
    "MERGED_KNOWLEDGE_SECTION_HEADINGS",
    "NOTES",
    "PRESERVED_ROOT_FILES",
    "PRESERVED_WIKI_PREFIXES",
    "REQUIRED_FIELDS_BY_FRONTMATTER",
    "SIGNALS",
    "SOURCE_H2_HEADINGS",
    "SOURCES",
    "TOOLS",
    "TOPICS",
    "CategorySpec",
    "all_category_specs",
    "category_folder_for_graph",
    "derived_key_for_graph_category",
    "graph_category_for_frontmatter",
    "is_lint_skipped_path",
    "is_managed_relative_path",
    "is_preserved_wiki_path",
    "required_fields_for",
    "required_h2_headings_for",
    "spec_for_frontmatter",
    "spec_for_graph",
]
