"""Read-only artifact retention inventory for wiki operations."""

from __future__ import annotations

import os
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Literal

from src.wiki_paths.config import WikiPaths

DataClass = Literal["canonical", "generated", "temporary"]
CLEANUP_BLOCKED_REASON = (
    "real cleanup requires hatch run wiki-cleanup --after-release <release_id> --yes"
)


@dataclass(frozen=True)
class ArtifactAreaDefinition:
    """Static metadata for one managed artifact area."""

    key: str
    path: Path
    data_class: DataClass
    purpose: str
    cleanup_policy: str
    must_backup: bool
    git_policy: str
    optional: bool = False


@dataclass(frozen=True)
class ArtifactAreaStatus:
    """Filesystem inventory for one artifact area."""

    key: str
    path: Path
    data_class: DataClass
    purpose: str
    cleanup_policy: str
    must_backup: bool
    git_policy: str
    exists: bool
    file_count: int
    byte_count: int
    newest_mtime: float | None
    oldest_mtime: float | None
    warnings: list[str]

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable area status payload."""
        payload = asdict(self)
        payload["path"] = str(self.path)
        return payload


@dataclass(frozen=True)
class CleanupPreflight:
    """Read-only cleanup preflight summary."""

    temporary_file_count: int
    temporary_byte_count: int
    cleanup_candidate_count: int
    cleanup_candidate_bytes: int
    cleanup_blocked_reason: str

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable cleanup preflight payload."""
        return asdict(self)


@dataclass(frozen=True)
class RetentionInventory:
    """Full artifact retention inventory."""

    areas: list[ArtifactAreaStatus]
    totals_by_class: dict[str, dict[str, int]]
    cleanup_preflight: CleanupPreflight
    warnings: list[str]

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable retention inventory payload."""
        return {
            "areas": [area.to_dict() for area in self.areas],
            "totals_by_class": self.totals_by_class,
            "cleanup_preflight": self.cleanup_preflight.to_dict(),
            "warnings": list(self.warnings),
        }


def artifact_area_definitions(paths: WikiPaths) -> list[ArtifactAreaDefinition]:
    """Build artifact area definitions from resolved wiki paths."""
    knowledge_root = paths.knowledge_root
    definitions = [
        ArtifactAreaDefinition(
            key="raw_readwise",
            path=paths.raw_dir,
            data_class="canonical",
            purpose="Original Readwise markdown/html exports",
            cleanup_policy="never",
            must_backup=True,
            git_policy="do not commit by default",
        ),
        ArtifactAreaDefinition(
            key="reviews",
            path=paths.reviews_dir,
            data_class="canonical",
            purpose="Human-reviewed extraction artifacts",
            cleanup_policy="never",
            must_backup=True,
            git_policy="commit selectively",
        ),
        ArtifactAreaDefinition(
            key="synthesis_cache",
            path=paths.synthesis_dir,
            data_class="canonical",
            purpose="Stage 2 synthesis cache entries",
            cleanup_policy="never",
            must_backup=True,
            git_policy="commit selectively",
        ),
        ArtifactAreaDefinition(
            key="render_graph",
            path=paths.graph_path,
            data_class="generated",
            purpose="Machine-readable wiki render graph export",
            cleanup_policy="replaced by render",
            must_backup=False,
            git_policy="commit selectively",
        ),
        ArtifactAreaDefinition(
            key="render_manifest",
            path=paths.manifest_path,
            data_class="generated",
            purpose="Advisory wiki render manifest",
            cleanup_policy="replaced by render",
            must_backup=False,
            git_policy="commit selectively",
        ),
        ArtifactAreaDefinition(
            key="wiki",
            path=paths.wiki_dir,
            data_class="generated",
            purpose="Generated Obsidian wiki including sources/<source_id>.md full text",
            cleanup_policy="regenerated by render",
            must_backup=False,
            git_policy="commit in vault/release flow",
        ),
        ArtifactAreaDefinition(
            key="synthesis_previews",
            path=paths.preview_dir,
            data_class="temporary",
            purpose="Human-readable synthesis preview markdown",
            cleanup_policy="clean after release",
            must_backup=False,
            git_policy="do not commit by default",
        ),
        ArtifactAreaDefinition(
            key="synthesis_runs",
            path=paths.run_dir,
            data_class="temporary",
            purpose="Stage 2 synthesis batch audit reports",
            cleanup_policy="keep latest / TTL later",
            must_backup=False,
            git_policy="do not commit by default",
        ),
        ArtifactAreaDefinition(
            key="synthesis_backups",
            path=paths.backup_dir,
            data_class="temporary",
            purpose="Synthesis backup artifacts",
            cleanup_policy="clean after release",
            must_backup=False,
            git_policy="do not commit by default",
        ),
        ArtifactAreaDefinition(
            key="synthesis_prompts",
            path=knowledge_root / "state" / "synthesis_prompts",
            data_class="temporary",
            purpose="Saved synthesis prompt preview artifacts",
            cleanup_policy="manual / TTL later",
            must_backup=False,
            git_policy="do not commit by default",
            optional=True,
        ),
        ArtifactAreaDefinition(
            key="ingest_batches",
            path=knowledge_root / "state" / "ingest_batches",
            data_class="temporary",
            purpose="Ingest pre-analysis batch logs",
            cleanup_policy="TTL later",
            must_backup=False,
            git_policy="do not commit by default",
            optional=True,
        ),
    ]
    return definitions


def collect_retention_inventory(paths: WikiPaths) -> RetentionInventory:
    """Collect a read-only artifact retention inventory."""
    areas = [inventory_area(definition) for definition in artifact_area_definitions(paths)]
    warnings = _collect_inventory_warnings(areas)
    totals_by_class = _totals_by_class(areas)
    cleanup_preflight = _build_cleanup_preflight(areas)
    return RetentionInventory(
        areas=areas,
        totals_by_class=totals_by_class,
        cleanup_preflight=cleanup_preflight,
        warnings=warnings,
    )


def inventory_area(definition: ArtifactAreaDefinition) -> ArtifactAreaStatus:
    """Inventory one artifact area using read-only filesystem metadata."""
    stats = _path_inventory_stats(definition.path)
    warnings: list[str] = []
    if definition.data_class == "canonical" and not stats.exists and not definition.optional:
        warnings.append(f"Canonical path missing: {definition.key}.")
    return ArtifactAreaStatus(
        key=definition.key,
        path=definition.path,
        data_class=definition.data_class,
        purpose=definition.purpose,
        cleanup_policy=definition.cleanup_policy,
        must_backup=definition.must_backup,
        git_policy=definition.git_policy,
        exists=stats.exists,
        file_count=stats.file_count,
        byte_count=stats.byte_count,
        newest_mtime=stats.newest_mtime,
        oldest_mtime=stats.oldest_mtime,
        warnings=warnings,
    )


def build_retention_recommendations(inventory: RetentionInventory) -> list[str]:
    """Return conservative recommendations derived from retention inventory."""
    recommendations: list[str] = []
    if inventory.cleanup_preflight.temporary_file_count > 0:
        recommendations.append(
            "Temporary artifacts are present; inspect cleanup candidates with "
            "`hatch run wiki-cleanup --dry-run` after a release manifest exists.",
        )
    for warning in inventory.warnings:
        if warning.startswith("Canonical path missing:"):
            recommendations.append(f"{warning} Verify path configuration before continuing.")
    return recommendations


def format_retention_text(inventory: RetentionInventory) -> str:
    """Render a concise human-readable retention inventory section."""
    lines = ["Retention Inventory"]
    for data_class in ("canonical", "generated", "temporary"):
        totals = inventory.totals_by_class.get(data_class, {"areas": 0, "files": 0, "bytes": 0})
        lines.append(
            f"- {data_class}: {totals['areas']} areas, {totals['files']} files, "
            f"{_format_bytes(totals['bytes'])}"
        )
    preflight = inventory.cleanup_preflight
    if preflight.temporary_file_count:
        lines.append(
            f"- cleanup preflight: temporary artifacts present; {preflight.cleanup_blocked_reason}"
        )
    else:
        lines.append(
            f"- cleanup preflight: no temporary artifacts present; "
            f"{preflight.cleanup_blocked_reason}"
        )
    lines.append("")
    lines.append("Areas")
    for area in inventory.areas:
        presence = "present" if area.exists else "missing"
        lines.append(
            f"- {area.key}: {area.data_class}, {presence}, {area.file_count} files, "
            f"{area.cleanup_policy}"
        )
    if inventory.warnings:
        lines.append("")
        lines.append("Retention warnings")
        lines.extend(f"- {warning}" for warning in inventory.warnings)
    return "\n".join(lines)


@dataclass(frozen=True)
class _PathInventoryStats:
    """Filesystem stats for one inventoried path."""

    exists: bool
    file_count: int
    byte_count: int
    newest_mtime: float | None
    oldest_mtime: float | None


def _path_inventory_stats(path: Path) -> _PathInventoryStats:
    """Count files and bytes for a path without following symlinked directories."""
    if not path.exists():
        return _PathInventoryStats(
            exists=False,
            file_count=0,
            byte_count=0,
            newest_mtime=None,
            oldest_mtime=None,
        )
    if path.is_file():
        stat = path.stat()
        mtime = stat.st_mtime
        return _PathInventoryStats(
            exists=True,
            file_count=1,
            byte_count=stat.st_size,
            newest_mtime=mtime,
            oldest_mtime=mtime,
        )
    if not path.is_dir():
        return _PathInventoryStats(
            exists=True,
            file_count=0,
            byte_count=0,
            newest_mtime=None,
            oldest_mtime=None,
        )
    file_count = 0
    byte_count = 0
    newest_mtime: float | None = None
    oldest_mtime: float | None = None
    for root, dirnames, filenames in os.walk(path, followlinks=False):
        root_path = Path(root)
        dirnames[:] = [name for name in dirnames if not (root_path / name).is_symlink()]
        for filename in filenames:
            file_path = root_path / filename
            if file_path.is_symlink():
                continue
            try:
                stat = file_path.stat()
            except OSError:
                continue
            file_count += 1
            byte_count += stat.st_size
            newest_mtime = (
                stat.st_mtime if newest_mtime is None else max(newest_mtime, stat.st_mtime)
            )
            oldest_mtime = (
                stat.st_mtime if oldest_mtime is None else min(oldest_mtime, stat.st_mtime)
            )
    return _PathInventoryStats(
        exists=True,
        file_count=file_count,
        byte_count=byte_count,
        newest_mtime=newest_mtime,
        oldest_mtime=oldest_mtime,
    )


def _totals_by_class(areas: list[ArtifactAreaStatus]) -> dict[str, dict[str, int]]:
    """Aggregate file and byte totals by data class."""
    totals: dict[str, dict[str, int]] = {
        "canonical": {"areas": 0, "files": 0, "bytes": 0},
        "generated": {"areas": 0, "files": 0, "bytes": 0},
        "temporary": {"areas": 0, "files": 0, "bytes": 0},
    }
    for area in areas:
        bucket = totals[area.data_class]
        if area.exists:
            bucket["areas"] += 1
        bucket["files"] += area.file_count
        bucket["bytes"] += area.byte_count
    return totals


def _build_cleanup_preflight(areas: list[ArtifactAreaStatus]) -> CleanupPreflight:
    """Build read-only cleanup preflight information."""
    temporary_areas = [area for area in areas if area.data_class == "temporary"]
    temporary_file_count = sum(area.file_count for area in temporary_areas)
    temporary_byte_count = sum(area.byte_count for area in temporary_areas)
    return CleanupPreflight(
        temporary_file_count=temporary_file_count,
        temporary_byte_count=temporary_byte_count,
        cleanup_candidate_count=0,
        cleanup_candidate_bytes=0,
        cleanup_blocked_reason=CLEANUP_BLOCKED_REASON,
    )


def _collect_inventory_warnings(areas: list[ArtifactAreaStatus]) -> list[str]:
    """Collect top-level retention warnings."""
    warnings: list[str] = []
    for area in areas:
        warnings.extend(area.warnings)
    return warnings


def _format_bytes(byte_count: int) -> str:
    """Format a byte count for human-readable output."""
    if byte_count < 1024:
        return f"{byte_count} B"
    if byte_count < 1024 * 1024:
        return f"{byte_count / 1024:.1f} KB"
    if byte_count < 1024 * 1024 * 1024:
        return f"{byte_count / (1024 * 1024):.1f} MB"
    return f"{byte_count / (1024 * 1024 * 1024):.1f} GB"
